### ISSUE TITLE
I received duplicate messages after restarting the application

### ISSUE THREAD

**Issue by Shonke** [calebboyd/redis-x-stream#4]
After the application restarts, I repeatedly receive messages that have already been processed

```javascript
const { RedisStream } = require('redis-x-stream')
const stream1 = new RedisStream({ streams: ['stream1'] })

for await (const [name, [id, payload]] of stream1) {
    console.log(name, id, payload)
}
```

```bash
$ node code.js
stream1 1687444127373-0 [ 'k', 'value1' ]
^C
$ node code.js
stream1 1687444127373-0 [ 'k', 'value1' ]
^C
```

**Comment by calebboyd** [comment]
Unless you track the cursor yourself it defaults to zero (the beginning of the stream)

You can provide it explicitly 

```javascript
const stream1 = new RedisStream({
  streams: { stream1: '1689286839801' }  
})
```

Or,
If you want redis to track your progress you'd need to use [consumer groups](https://redis.io/docs/data-types/streams/#consumer-groups).

With this library the options for that are `consumer`. `ackOnIterate` will queue `count` number of acks which it will batch back to redis when fetching more items.
Calling `.flush` ensures this happens when your stream or program is complete.

```javascript
const { RedisStream } = require('redis-x-stream')
const stream1 = new RedisStream({
  streams: ['stream1'],
  consumer: 'my-consumer',
  ackOnIterate: true,
})


for await (const [name, [id, payload]] of stream1) {
    console.log(name, id, payload)
}

//before process exit
await stream1.flush()
```
